# PyWebTransport GitHub Issue Template Configuration

blank_issues_enabled: false
contact_links:
  - name: Question or Support Request
    url: https://github.com/lemonsterfy/pywebtransport/discussions
    about: Please ask and answer questions here. The issue tracker is reserved for bugs and feature requests.
